-- AlterTable
ALTER TABLE `attendance` ADD COLUMN `clarity` VARCHAR(191) NULL,
    ADD COLUMN `date` VARCHAR(191) NULL,
    ADD COLUMN `endTime` VARCHAR(191) NULL,
    ADD COLUMN `feedback` TEXT NULL,
    ADD COLUMN `instructorArrival` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `notes` VARCHAR(191) NULL,
    ADD COLUMN `rating` INTEGER NULL,
    ADD COLUMN `reason` VARCHAR(191) NULL,
    ADD COLUMN `relevance` VARCHAR(191) NULL,
    ADD COLUMN `session` VARCHAR(191) NULL,
    ADD COLUMN `startTime` VARCHAR(191) NULL,
    ADD COLUMN `time` VARCHAR(191) NULL;
